//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assign12Client.SSOS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca")]
    public partial class SubjectOutlineServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Exception subjectOutlineServiceException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubjectOutlineServiceException", IsNullable=true, Order=0)]
        public Exception SubjectOutlineServiceException1 {
            get {
                return this.subjectOutlineServiceException1Field;
            }
            set {
                this.subjectOutlineServiceException1Field = value;
                this.RaisePropertyChanged("SubjectOutlineServiceException1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca/xsd")]
    public partial class SubjectOutline : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accommodationForStudentsWithDisabilitiesField;
        
        private string approvedByField;
        
        private string cheatingAndPlagiarismField;
        
        private string commonLastReviewDateField;
        
        private string commonLastRevisionDateField;
        
        private string creditStatusField;
        
        private string customSectionField;
        
        private string customSectionTitleField;
        
        private string discriminationHarassmentField;
        
        private string essentialEmployabilitySkillsField;
        
        private string learningOutcomesField;
        
        private string modeOfInstructionField;
        
        private string modesOfEvaluationField;
        
        private string prerequisitesField;
        
        private string prescribedTextsField;
        
        private string promotionPolicyField;
        
        private bool publishedField;
        
        private bool publishedFieldSpecified;
        
        private string referenceMaterialField;
        
        private string requiredSuppliesField;
        
        private string schoolCodeField;
        
        private string schoolLastReviewDateField;
        
        private string schoolLastRevisionDateField;
        
        private string schoolNameField;
        
        private string subjectCodeField;
        
        private string subjectDescriptionField;
        
        private string subjectNameField;
        
        private string subjectTitleField;
        
        private string topicOutlineField;
        
        private string yearSemesterField;
        
        private string yearSemesterLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string accommodationForStudentsWithDisabilities {
            get {
                return this.accommodationForStudentsWithDisabilitiesField;
            }
            set {
                this.accommodationForStudentsWithDisabilitiesField = value;
                this.RaisePropertyChanged("accommodationForStudentsWithDisabilities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string approvedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
                this.RaisePropertyChanged("approvedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string cheatingAndPlagiarism {
            get {
                return this.cheatingAndPlagiarismField;
            }
            set {
                this.cheatingAndPlagiarismField = value;
                this.RaisePropertyChanged("cheatingAndPlagiarism");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string commonLastReviewDate {
            get {
                return this.commonLastReviewDateField;
            }
            set {
                this.commonLastReviewDateField = value;
                this.RaisePropertyChanged("commonLastReviewDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string commonLastRevisionDate {
            get {
                return this.commonLastRevisionDateField;
            }
            set {
                this.commonLastRevisionDateField = value;
                this.RaisePropertyChanged("commonLastRevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string creditStatus {
            get {
                return this.creditStatusField;
            }
            set {
                this.creditStatusField = value;
                this.RaisePropertyChanged("creditStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string customSection {
            get {
                return this.customSectionField;
            }
            set {
                this.customSectionField = value;
                this.RaisePropertyChanged("customSection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string customSectionTitle {
            get {
                return this.customSectionTitleField;
            }
            set {
                this.customSectionTitleField = value;
                this.RaisePropertyChanged("customSectionTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string discriminationHarassment {
            get {
                return this.discriminationHarassmentField;
            }
            set {
                this.discriminationHarassmentField = value;
                this.RaisePropertyChanged("discriminationHarassment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string essentialEmployabilitySkills {
            get {
                return this.essentialEmployabilitySkillsField;
            }
            set {
                this.essentialEmployabilitySkillsField = value;
                this.RaisePropertyChanged("essentialEmployabilitySkills");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string learningOutcomes {
            get {
                return this.learningOutcomesField;
            }
            set {
                this.learningOutcomesField = value;
                this.RaisePropertyChanged("learningOutcomes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string modeOfInstruction {
            get {
                return this.modeOfInstructionField;
            }
            set {
                this.modeOfInstructionField = value;
                this.RaisePropertyChanged("modeOfInstruction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string modesOfEvaluation {
            get {
                return this.modesOfEvaluationField;
            }
            set {
                this.modesOfEvaluationField = value;
                this.RaisePropertyChanged("modesOfEvaluation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string prerequisites {
            get {
                return this.prerequisitesField;
            }
            set {
                this.prerequisitesField = value;
                this.RaisePropertyChanged("prerequisites");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string prescribedTexts {
            get {
                return this.prescribedTextsField;
            }
            set {
                this.prescribedTextsField = value;
                this.RaisePropertyChanged("prescribedTexts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string promotionPolicy {
            get {
                return this.promotionPolicyField;
            }
            set {
                this.promotionPolicyField = value;
                this.RaisePropertyChanged("promotionPolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool published {
            get {
                return this.publishedField;
            }
            set {
                this.publishedField = value;
                this.RaisePropertyChanged("published");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishedSpecified {
            get {
                return this.publishedFieldSpecified;
            }
            set {
                this.publishedFieldSpecified = value;
                this.RaisePropertyChanged("publishedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string referenceMaterial {
            get {
                return this.referenceMaterialField;
            }
            set {
                this.referenceMaterialField = value;
                this.RaisePropertyChanged("referenceMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string requiredSupplies {
            get {
                return this.requiredSuppliesField;
            }
            set {
                this.requiredSuppliesField = value;
                this.RaisePropertyChanged("requiredSupplies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string schoolCode {
            get {
                return this.schoolCodeField;
            }
            set {
                this.schoolCodeField = value;
                this.RaisePropertyChanged("schoolCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string schoolLastReviewDate {
            get {
                return this.schoolLastReviewDateField;
            }
            set {
                this.schoolLastReviewDateField = value;
                this.RaisePropertyChanged("schoolLastReviewDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string schoolLastRevisionDate {
            get {
                return this.schoolLastRevisionDateField;
            }
            set {
                this.schoolLastRevisionDateField = value;
                this.RaisePropertyChanged("schoolLastRevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string schoolName {
            get {
                return this.schoolNameField;
            }
            set {
                this.schoolNameField = value;
                this.RaisePropertyChanged("schoolName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string subjectCode {
            get {
                return this.subjectCodeField;
            }
            set {
                this.subjectCodeField = value;
                this.RaisePropertyChanged("subjectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string subjectDescription {
            get {
                return this.subjectDescriptionField;
            }
            set {
                this.subjectDescriptionField = value;
                this.RaisePropertyChanged("subjectDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string subjectName {
            get {
                return this.subjectNameField;
            }
            set {
                this.subjectNameField = value;
                this.RaisePropertyChanged("subjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string subjectTitle {
            get {
                return this.subjectTitleField;
            }
            set {
                this.subjectTitleField = value;
                this.RaisePropertyChanged("subjectTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string topicOutline {
            get {
                return this.topicOutlineField;
            }
            set {
                this.topicOutlineField = value;
                this.RaisePropertyChanged("topicOutline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string yearSemester {
            get {
                return this.yearSemesterField;
            }
            set {
                this.yearSemesterField = value;
                this.RaisePropertyChanged("yearSemester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string yearSemesterLabel {
            get {
                return this.yearSemesterLabelField;
            }
            set {
                this.yearSemesterLabelField = value;
                this.RaisePropertyChanged("yearSemesterLabel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", ConfigurationName="SSOS.SubjectOutlineServicePortType")]
    public interface SubjectOutlineServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getOutline", ReplyAction="urn:getOutlineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Assign12Client.SSOS.SubjectOutlineServiceException), Action="urn:getOutlineSubjectOutlineServiceException", Name="SubjectOutlineServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Assign12Client.SSOS.getOutlineResponse getOutline(Assign12Client.SSOS.getOutlineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getOutline", ReplyAction="urn:getOutlineResponse")]
        System.Threading.Tasks.Task<Assign12Client.SSOS.getOutlineResponse> getOutlineAsync(Assign12Client.SSOS.getOutlineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOutline", WrapperNamespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", IsWrapped=true)]
    public partial class getOutlineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subjectCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string yearSemester;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string schoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", Order=3)]
        public bool publishedOnly;
        
        public getOutlineRequest() {
        }
        
        public getOutlineRequest(string subjectCode, string yearSemester, string schoolCode, bool publishedOnly) {
            this.subjectCode = subjectCode;
            this.yearSemester = yearSemester;
            this.schoolCode = schoolCode;
            this.publishedOnly = publishedOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOutlineResponse", WrapperNamespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", IsWrapped=true)]
    public partial class getOutlineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.ws.subjectoutlines.itt.senecacollege.ca", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Assign12Client.SSOS.SubjectOutline @return;
        
        public getOutlineResponse() {
        }
        
        public getOutlineResponse(Assign12Client.SSOS.SubjectOutline @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubjectOutlineServicePortTypeChannel : Assign12Client.SSOS.SubjectOutlineServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubjectOutlineServicePortTypeClient : System.ServiceModel.ClientBase<Assign12Client.SSOS.SubjectOutlineServicePortType>, Assign12Client.SSOS.SubjectOutlineServicePortType {
        
        public SubjectOutlineServicePortTypeClient() {
        }
        
        public SubjectOutlineServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubjectOutlineServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectOutlineServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectOutlineServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign12Client.SSOS.getOutlineResponse Assign12Client.SSOS.SubjectOutlineServicePortType.getOutline(Assign12Client.SSOS.getOutlineRequest request) {
            return base.Channel.getOutline(request);
        }
        
        public Assign12Client.SSOS.SubjectOutline getOutline(string subjectCode, string yearSemester, string schoolCode, bool publishedOnly) {
            Assign12Client.SSOS.getOutlineRequest inValue = new Assign12Client.SSOS.getOutlineRequest();
            inValue.subjectCode = subjectCode;
            inValue.yearSemester = yearSemester;
            inValue.schoolCode = schoolCode;
            inValue.publishedOnly = publishedOnly;
            Assign12Client.SSOS.getOutlineResponse retVal = ((Assign12Client.SSOS.SubjectOutlineServicePortType)(this)).getOutline(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign12Client.SSOS.getOutlineResponse> Assign12Client.SSOS.SubjectOutlineServicePortType.getOutlineAsync(Assign12Client.SSOS.getOutlineRequest request) {
            return base.Channel.getOutlineAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign12Client.SSOS.getOutlineResponse> getOutlineAsync(string subjectCode, string yearSemester, string schoolCode, bool publishedOnly) {
            Assign12Client.SSOS.getOutlineRequest inValue = new Assign12Client.SSOS.getOutlineRequest();
            inValue.subjectCode = subjectCode;
            inValue.yearSemester = yearSemester;
            inValue.schoolCode = schoolCode;
            inValue.publishedOnly = publishedOnly;
            return ((Assign12Client.SSOS.SubjectOutlineServicePortType)(this)).getOutlineAsync(inValue);
        }
    }
}
